<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:TalendMetadata="http://www.talend.org/metadata/connection/2010" xmlns:orgomg.cwm.objectmodel.core="http:///orgomg/cwm/objectmodel/core.ecore" xmlns:orgomg.cwm.resource.relational="http:///orgomg/cwm/resource/relational.ecore">
  <TalendMetadata:DatabaseConnection xmi:id="_XIZSMN9OEeid7v2-FZr9SQ" name="Mysql_local" supplierDependency="_XIZSPt9OEeid7v2-FZr9SQ" id="_wp_scN1GEeigRf1EgGbOLg" label="Mysql_local" dataPackage="_XIZSP99OEeid7v2-FZr9SQ" ContextMode="true" ContextId="_lwd2wN1JEeiJVaJ0nfyOPQ" contextName="Dev" DatabaseType="MySQL" DriverClass="org.gjt.mm.mysql.Driver" URL="jdbc:mysql://localhost:3306/volvo?noDatetimeStringSync=true" dbVersionString="MYSQL_5" Port="context.Mysql_local_Port" Username="context.Mysql_local_Login" Password="context.Mysql_local_Password" ServerName="context.Mysql_local_Server" DatasourceName="" FileFieldName="" SID="context.Mysql_local_Database" SqlSynthax="" StringQuote="" NullChar="" DbmsId="mysql_id" ProductId="MYSQL" AdditionalParams="context.Mysql_local_AdditionalParams" StandardSQL="true" SQLMode="false" UiSchema="">
    <taggedValue xmi:id="_XIZSMd9OEeid7v2-FZr9SQ" tag="Is Conn Need Reload" value="false"/>
    <taggedValue xmi:id="_XIZSMt9OEeid7v2-FZr9SQ" tag="package filter" value=""/>
    <taggedValue xmi:id="_XIZSM99OEeid7v2-FZr9SQ" tag="Status" value=""/>
    <taggedValue xmi:id="_XIZSNN9OEeid7v2-FZr9SQ" tag="Version" value="0.1"/>
    <taggedValue xmi:id="_XIZSNd9OEeid7v2-FZr9SQ" tag="Purpose" value=""/>
    <taggedValue xmi:id="_XIZSNt9OEeid7v2-FZr9SQ" tag="Description" value=""/>
    <taggedValue xmi:id="_XIZSN99OEeid7v2-FZr9SQ" tag="Author" value=""/>
    <taggedValue xmi:id="_XIZSON9OEeid7v2-FZr9SQ" tag="otherParameter"/>
    <taggedValue xmi:id="_XIZSOd9OEeid7v2-FZr9SQ" tag="DB ProductName" value="MySQL"/>
    <taggedValue xmi:id="_XIZSOt9OEeid7v2-FZr9SQ" tag="DB ProductVersion" value="5.7.24-log"/>
    <taggedValue xmi:id="_XIZSO99OEeid7v2-FZr9SQ" tag="DB IdentifierQuoteString" value="`"/>
    <parameters xmi:id="_XIZSPN9OEeid7v2-FZr9SQ" key="CONN_PARA_KEY_USERNAME" value="context.Mysql_local_Login"/>
    <parameters xmi:id="_XIZSPd9OEeid7v2-FZr9SQ" key="CONN_PARA_KEY_MAPRDB_TABLE_NS_MAPPING" value=""/>
  </TalendMetadata:DatabaseConnection>
  <orgomg.cwm.objectmodel.core:Dependency xmi:id="_XIZSPt9OEeid7v2-FZr9SQ" kind="Usage" supplier="_XIZSMN9OEeid7v2-FZr9SQ"/>
  <orgomg.cwm.resource.relational:Catalog xmi:id="_XIZSP99OEeid7v2-FZr9SQ" name="volvo" dataManager="_XIZSMN9OEeid7v2-FZr9SQ"/>
</xmi:XMI>
